# Generated by Django 3.1.7 on 2021-04-21 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_message', '0004_auto_20210421_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
